apiVersion: apps/v1
kind: Deployment
metadata:
  name: glaurung-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glaurung
  template:
    metadata:
      labels:
        app: glaurung
    spec:
      containers:
      - name: glaurung-container
        image: solamarpreet/glaurung:12345
