name: cicd

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set image tag
        id: imagetag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
      -
        name: Decrypt env
        run: ./scripts/decrypt_env.sh
        env:
          ENV_SECRET_PASSPHRASE: ${{ secrets.ENV_SECRET_PASSPHRASE }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: solamarpreet/glaurung:${{ env.IMAGE_TAG }}
      -
        name: Setup Kube Config
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      -
        name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
          secret-name: 'docker-registry'
          container-registry-url: 'docker.io'
          container-registry-username: ${{ secrets.DOCKER_USER }}
          container-registry-password: ${{ secrets.DOCKER_TOKEN }}
        id: create-secret
      -
        name: Deploy to K8S cluster
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
              kubernetes/
          images: solamarpreet/glaurung:${{ env.IMAGE_TAG }}
          imagepullsecrets: |
              docker-registry
          skip-tls-verify: true
          annotate-namespace: false